package suike.suikefoxfriend;

import suike.suikefoxfriend.asm.*;
import suike.suikefoxfriend.expand.Examine;
import suike.suikefoxfriend.packet.PacketHandler;

import net.minecraft.client.Minecraft;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

@Mod(modid = SuiKe.MODID, name = SuiKe.NAME, version = SuiKe.VERSION)
public class SuiKe {

    public static final String MODID = "suikefoxfriend";
    public static final String NAME = "§e狐友";
    public static final String VERSION = "1.0.7"; /// 已更新 1.0.6
    public static final String ACCEPTED_VERSIONS = "[1.12.2]";

    public static boolean isServer = true;
    public static boolean isZhCn;

    static { new ASMCoreMod(); }

    @Mod.EventHandler
    public void Construction(FMLConstructionEvent event) {
        if (FMLCommonHandler.instance().getSide().isClient()) {
            PacketHandler.registerClientPackets();
            isServer = false;
        }

        Examine.examine();
        ASMData.initConditionMap();
    }

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        if (!isServer) {
            String language = Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage().getLanguageCode();
            isZhCn = (language.equals("zh_cn") || language.equals("zh_tw") || language.equals("zh_hk"));

            模组简介(event);
        }
    }

    @Mod.EventHandler
    public void onServerStart(FMLServerStartingEvent event) {
        if (isServer) {
            PacketHandler.registerServerPackets();
        }
    }

// 模组简介
    private static void 模组简介(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = "§e" + NAME;
        event.getModMetadata().url = "";
        event.getModMetadata().updateUrl = "";
        event.getModMetadata().logoFile = "assets/suikefoxfriend/textures/gui/ico.png";

        if (SuiKe.isZhCn) {
            event.getModMetadata().name = "§e狐友";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§d模组作者: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§e相关链接:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/19114.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/fox-friend" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/fox-friend" + "\n"
                    + "--------------------------------------------------" + "\n"
            ;
        } else {
            event.getModMetadata().name = "§eFoxFriend";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§dMod author: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§eRelated links:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/19114.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/fox-friend" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/fox-friend" + "\n"
                    + "--------------------------------------------------" + "\n"
            ;
        }
    }
}